fix baggageclaim cgroup setup failure
this appears to fail if garden is colocated and the jobs are started
concurrently enough for devices to already be in use when trying to
permit device usage

Signed-off-by: Corbin Halliwill <challiwill@pivotal.io>

diff --git a/jobs/baggageclaim/templates/baggageclaim_ctl.erb b/jobs/baggageclaim/templates/baggageclaim_ctl.erb
--- a/jobs/baggageclaim/templates/baggageclaim_ctl.erb
+++ b/jobs/baggageclaim/templates/baggageclaim_ctl.erb
@@ -40,7 +40,9 @@ function permit_device_control() {
   fi
 
   # permit our cgroup to do everything with all devices
-  echo a > ${cgroup_dir}${devices_subdir}/devices.allow
+  # ignore failure in case something has already done this; echo appears to
+  # return EINVAL, possibly because devices this affects are already in use
+  echo a > ${cgroup_dir}${devices_subdir}/devices.allow || true
 }
 
 case $1 in
