attempt to mount tmpfs for pg scratch space
this brings the db suite down from 5m to 1m

diff --git a/ci/scripts/atc-go b/ci/scripts/atc-go
--- a/ci/scripts/atc-go
+++ b/ci/scripts/atc-go
@@ -6,6 +6,11 @@ set -e -x
 export GOPATH=$PWD/concourse
 export PATH=$GOPATH/bin:$PATH
 
+mkdir /tmp/concourse-pg-runner
+if ! mount -t tmpfs none /tmp/concourse-pg-runner; then
+  echo 'failed to mount tmpfs for pg. this is OK, db suite will just be slow'
+fi
+
 pushd ${GOPATH}/src/github.com/concourse/atc
   go install github.com/onsi/ginkgo/ginkgo
   xvfb-run ginkgo -r -p -race "$@"
