ci: get fly-build-* tasks working
made final-version an optional input for easier testing with `fly
execute`

diff --git a/ci/tasks/scripts/fly-build b/ci/tasks/scripts/fly-build
--- a/ci/tasks/scripts/fly-build
+++ b/ci/tasks/scripts/fly-build
@@ -3,23 +3,30 @@
 
 set -e -x
 
-export GOPATH=$PWD/concourse
-export PATH=$PWD/concourse/bin:$PATH
+export GOPATH=$PWD/gopath
+export PATH=$PWD/gopath/bin:$PATH
 
-# for Go on the Darwin worker
-export PATH=/usr/local/bin:$PATH
-
-final_version="$(cat final-version/version)"
 platform="$(go env GOOS)"
 arch="$(go env GOARCH)"
 
-filename="fly_${platform}_${arch}"
+output="$PWD/fly-${platform}"
 
-cd "${platform}-binary"
+buildflags=""
+if [ -e final-version/version ]; then
+  final_version="$(cat final-version/version)"
+  buildflags="-ldflags \"-X github.com/concourse/fly/version.Version=${final_version}\""
+fi
 
-go build \
-  -ldflags "-X github.com/concourse/fly/version.Version=${final_version}" \
-  -o "$filename" \
-  github.com/concourse/fly
+pushd concourse
+  CGO_ENABLED=0 go build $buildflags -o $output/fly ./fly
+  if which ldd && ldd $output/fly 2>/dev/null; then
+    echo "binary is not static; aborting"
+    exit 1
+  fi
+popd
 
-shasum "$filename" > "${filename}.sha1"
+pushd $output
+  archive=fly-$platform-$arch.tgz
+  tar -czf $archive fly
+  shasum "$archive" > "${archive}.sha1"
+popd
